# Generated by Django 3.1 on 2021-09-06 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textparse', '0002_auto_20210906_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='data',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='data',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='data',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
