# Generated by Django 3.1 on 2021-09-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=25)),
                ('start_time', models.CharField(max_length=25)),
                ('end_time', models.CharField(max_length=25)),
                ('duration', models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Records',
        ),
    ]
