# Generated by Django 3.1 on 2021-09-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210907_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='end_time',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
